repos:
-   repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
    - id: shell-lint
-   repo: git://github.com/alphagov/verify-travis-pre-commit-hook
    sha: master
    hooks:
    -   id: travis-yml-lint
