language: ruby
dist: trusty
sudo: required

rvm:
- 2.4.4
before_script:
  - gem install bundler -v 1.16.2
  - bundle exec hatchet ci:setup

script:
  - docker build --pull --file $(pwd)/Dockerfile .; docker run --rm -e "STACK=heroku-18" bash $TESTFOLDER
  - docker build --pull --file $(pwd)/Dockerfile.heroku-18 .; docker run --rm -e "STACK=heroku-18" bash $TESTFOLDER

jobs:
  include:
  - stage: Bash linting (shellcheck)
    sudo: false
    script: make check
  - stage: Hatchet Integration
    if: branch = master
    name: Run Hatchet
    script: "bundle exec rspec"
env:
  matrix:
    - TESTFOLDER=test/run-deps
    - TESTFOLDER=test/run-versions
    - TESTFOLDER=test/run-features
    - DOCKERFILE=Dockerfile.heroku-18
    - DOCKERFILE=Dockerfile
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=2
  global:
    - HATCHET_RETRIES=3
    - IS_RUNNING_ON_CI=true
    - HATCHET_APP_LIMIT=5
    - HATCHET_DEPLOY_STRATEGY=git
    - CI_NODE_TOTAL=2
    - secure: yjtlPE5FbVxTKnjUy/tZUBgSEf4qADD3QOxtgziuid73S0U/1IEXlMGFULsQzIjtlHKmHeywZqpVVEpthIH4RuT7uoX1Pb7SSM/g0T8fT3VoEFbFK1uYl0oZQbUS4Klxv9tPiumj8if3m6ULEGIz1X0wZcMOC0tMLwVCnwmap0E=
    - secure: ZeFTHWwnpIKE9nAqs88ocmiQh7bKce84lilGm5J23nf3N6V4wNyLwqlkvsM008WGBCaOg9AUx7ZunasT0ANsR5gLP3eV2UUg7ILdRgV2Gy13eNRFheC4PHdN92RqQ3aKoqlIv2K999xlhVjod0NzhkQQXB6PddfQINbuU7ks6As=
